# -*- coding: utf-8 -*-
"""Copy of Robinhood_Stockprice_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JWQoXUjmA2UgD1T4wmkESqzx63mdkKzk

In this Simple Beginner-Friendly Python Script, I use the `yfinance` API to download historical stockprice information for Robinhood Markets, Inc. (HOOD). Python library `Openpyxl` is used to convert the downloaded data into an Excel Spreadsheet and `google_colab` is used to download the spreadsheet.
This Script was developed on the **Google Colaboratory** Platform.
"""

!pip install yfinance
!pip install folium

import yfinance as yf

#set the ticker for Robinhood
hood = yf.Ticker("HOOD")

#get historical market data for Robinhood in the 1 day Interval range
robinhood_1d = hood.history(period="max", interval="1d", index=)

"""For Intraday data - like 5 minute Interval, `yfinance` dictates that the period must be set within the last 60 days. As such, 5m interval data will be downloaded from June 28 to August 25, 2022."""

RH_12 = hood.history(start="2022-06-28", end="2022-08-25", interval="5m")

#Resetting the Index to Ensure Datetime is Displayed as a Column
RH_12 = RH_12.reset_index()

print(RH_12.dtypes)

#Converting the datetime to string
RH_12['Datetime'] = RH_12['Datetime'].astype(str)

print(RH_12.dtypes)

"""Now; Using the `Openpyxl` and `Pandas` Libraries to load data into an Excel Sheet;"""

!pip install Openpyxl

#Creating a New Workbook with Three Sheets
from openpyxl import Workbook
data_wb = Workbook()

#####The line below sets the sheet to store dates in the ISO 8601 Format###################
data_wb.iso_dates = True  #important to ensure the 5-min data is stored with timezone data#
###########################################################################################

ws1 = data_wb.create_sheet("1D_data_all", 0)
ws2 = data_wb.create_sheet("5M-data_last60days", 1)

"""Loading The Pandas Dataframes into the Worksheet;"""

from openpyxl.utils.dataframe import dataframe_to_rows

for r in dataframe_to_rows(robinhood_1d, index=True, header=True):
    ws1.append(r)

for z in dataframe_to_rows(RH_12, index=False, header=True):
    ws2.append(z)

#Saving the Workbook
data_wb.save('RobinHood Historical Stock Data.xls')

"""Finally, Downloading the Workbook from Google Colab;"""

from google.colab import files
files.download('RobinHood Historical Stock Data.xls')