# -*- coding: utf-8 -*-
"""Portfolio and Investment Management Data Download

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BpER0kNBSiEWmvNAKBsXz6BtW7eTjgaf

This Notebook is specifically dedicated to the download of Financial Data from Yahoo Finance using the```Yahoo_fin``` API. Data Downloaded in this Form was Used to Make Investment Decisions on a broader Portfolio Creation and Management Project.
"""

#Installing the Necessary Libraries
!pip install yahoo_fin
!pip install folium

!pip install pandas as pd
!pip install_datetime as dt

from pandas import DataFrame

from yahoo_fin import stock_info as si

#Setting the Dates Intervals for data download
sd = '2017-05-18'
ed = '2022-05-18'

etf_list = ['VISVX', 'IBB', 'ICLN', 'SMH', 'MCHI', 'VHF', 'SHY', 'SPY']

visvx_etf = si.get_data('VISVX', start_date=sd, end_date=ed, index_as_date = True, interval="1mo")

ibb_etf = si.get_data('IBB', start_date=sd, end_date=ed, index_as_date = True, interval="1mo")
icln_etf = si.get_data('ICLN', start_date=sd, end_date=ed, index_as_date = True, interval="1mo")
smh_etf = si.get_data('SMH', start_date=sd, end_date=ed, index_as_date = True, interval="1mo")
mchi_etf = si.get_data('MCHI', start_date=sd, end_date=ed, index_as_date = True, interval="1mo")
shy_etf = si.get_data('SHY', start_date=sd, end_date=ed, index_as_date = True, interval="1mo")
spy_etf = si.get_data('SPY', start_date=sd, end_date=ed, index_as_date = True, interval="1mo")

"""Loading the Data in an Excel Spreadsheet;"""

!pip install Openpyxl

from openpyxl import Workbook

#Creating worksheets on the new Workbook
etfs_wb = Workbook()
ws1 = etfs_wb.create_sheet("visvx", 0)
ws2 = etfs_wb.create_sheet("ibb", 1)
ws3 = etfs_wb.create_sheet("icln", 2)
ws4 = etfs_wb.create_sheet("smh", 3)
ws5 = etfs_wb.create_sheet("mchi", 4)
ws6 = etfs_wb.create_sheet("shy", 5)
ws7 = etfs_wb.create_sheet("spy", 6)

#Downloading the Data into a Worksheet

from openpyxl.utils.dataframe import dataframe_to_rows

for a in dataframe_to_rows(visvx_etf, index=True, header=True):
  ws1.append(a)
for b in dataframe_to_rows(ibb_etf, index=True, header=True):
  ws2.append(b)
for c in dataframe_to_rows(icln_etf, index=True, header=True):
  ws3.append(c)

for d in dataframe_to_rows(smh_etf, index=True, header=True):
  ws4.append(d)
for e in dataframe_to_rows(mchi_etf, index=True, header=True):
  ws5.append(e)
for f in dataframe_to_rows(shy_etf, index=True, header=True):
  ws6.append(f)
for g in dataframe_to_rows(spy_etf, index=True, header=True):
  ws7.append(g)

#saving workbook
etfs_wb.save('ETF Portfolio Optimization data.xls')

#Downloading the workbook from google colab

from google.colab import files
files.download('ETF Portfolio Optimization data.xls')